### ISSUE TITLE
How did you become a digital nomad?

### ISSUE THREAD

**Issue by sindresorhus** [arnaudbenard/ama#3]

**Comment by arnaudbenard** [comment]
I think it started when I went from having a full-time job in a startup to freelancing. I was living in London and the cost of living was getting quite high. After freelancing for a while and I've noticed that I didn't really need to be in London and I could just travel. London is super expensive and it was becoming quite frustrating to pay so much money for a flat. 

It was easier than expected because I already had a company and a business bank account in the UK. Also following https://twitter.com/levelsio really helped me to open my eyes on the lifestyle. I guess it's easier to take the leap when you see that other people are doing it.

When I tell the story like that it sounds like I had a plan but not really. I pretty much quit my job, got some gigs and decided to travel around with my stuff. It took around 6 months to make it happen.
